### ISSUE TITLE
Hardcoded paths to commands in mdata.py 

### ISSUE THREAD

**Issue by dizz** [icclab/sdcadmin#1]
There are hardcoded paths in [mdata.py](https://github.com/icclab/sdcadmin/blob/master/sdcadmin/mdata.py) that fail on certain OSes. This results in failed updates. The OS that this exhibits is Ubuntu 12.04LTS.

For [example see here](https://github.com/icclab/sdcadmin/blob/master/sdcadmin/mdata.py#L21).

One proposed solution is to use the [`which`](https://savannah.gnu.org/projects/which/) command to set these correctly. E.g.

```
# MDATA_DELETE=/usr/sbin/mdata-delete
MDATA_DELETE=`which mdata-delete`

# SLEEP=/opt/local/bin/sleep
SLEEP=`which sleep`

# BASE64=/usr/bin/base64 # only used in linux
BASE64=`which base64`

# CHMOD=/bin/chmod
CHMOD=`which chmod`

# CAT=/bin/cat
CAT=`which cat`

# NOHUP=/bin/nohup
NOHUP=`which nohup`
```

This approach solves the issue in Ubuntu 12.04LTS

Can supply pull request if needed...

**Comment by michaelerne** [comment]
Should be fixed with 0ab33e90971dbe1df08215fa0caf975b7c546244.
